#  colors
#  <black>
#  <dark_blue>
#  <dark_green>
#  <dark_aqua>
#  <dark_red>
#  <dark_purple>
#  <gold>
#  <gray>
#  <blue>
#  <green>
#  <aqua>
#  <red>
#  <light_purple>
#  <yellow>
#  <white>
#  <gold>

global:
  spawn:
    location:



home-settings:
  set-home:
    message: "Home has been set to: <green><cords>"

  home:
    message: "Teleported to your <green>home!"

spawn-settings:
  spawn:
    message: "Teleported to <green>spawn!"

  set-spawn:
    message: "Spawn has been set to: <green><cords>"
