#  colors
#  <black>
#  <dark_blue>
#  <dark_green>
#  <dark_aqua>
#  <dark_red>
#  <dark_purple>
#  <gold>
#  <gray>
#  <blue>
#  <green>
#  <aqua>
#  <red>
#  <light_purple>
#  <yellow>
#  <white>
#  <gold>


set-home-settings:
  max-homes: 1
  message: "Home has been set to: <green><cords>"
