name: zCore
version: '1.0'
main: org.zysw.zCore.src.ZCore
api-version: '1.21'

commands:
  sethome:
    description: Set your current location as a home.
    usage: /sethome
    permission: zCore.setHome
    permission-message: You don't have permission to set a home.

  home:
    description: Teleport's you to your home.
    usage: /home
    permission: zCore.home
    permission-message: You don't have permission to teleport to home.

  setspawn:
    description: Set your current location as spawn.
    usage: /setspawn
    permission: zCore.setSpawn
    permission-message: You don't have permission to set spawn


  spawn:
    description: Teleport's you to spawn
    usage: /spawn
    permission: zCore.spawn
    permission-message: You don't have permission to teleport to spawn

  tpa:
    description: Sends a tpa request to a other player
    usage: /tpa <player>
    permission: zCore.tpa
    permission-message: You don't have permission to send a tpa request

  tpaccept:
    description: Accepts the tpa request from a other player
    usage: /tpaccept
    permission: zCore.tpAccept
    permission-message: You don't have permission to accept tpa requests

  tpadeny:
    description: Declines the tpa request from a other player
    usage: /tpadeny
    permission: zCore.tpaDecline
    permission-message: You don't have permission to decline tpa requests

  announce:
    description: Sends an announcement to chat
    usage: /announce <message>
    permission: zCore.announce
    permission-message: You don't have permission to send announcements!

  rtp:
    description: Teleport's you to a random location
    usage: /rtp
    permission: zCore.rtp
    permission-message: You don't have permission to teleport to a random location!

  invsee:
    description: Views another player's inventory
    usage: /invsee <player>
    permission: zCore.invsee
    permission-message: You don't have permission to view another player's inventory

  endersee:
    description: Views another player's enderchest
    usage: /endersee <player>
    permission: zCore.endersee
    permission-message: You don't have permission to view another player's enderchest


permissions:

  zCore.setHome:
    description: Allows the player to set homes.
    default: true

  zCore.home:
    description: Allows the player to teleport to their home.
    default: true


  zCore.setSpawn:
    description: Allows the player to set spawn
    default: op


  zCore.spawn:
    description: Allows the player to teleport to spawn
    default: true


  zCore.tpAccept:
    description: Allows player to accept the tpa request
    default: true


  zCore.tpaDeny:
    description: Allows player to decline the tpa request
    default: true


  zCore.tpa:
    description: Allows player to send a tpa request to other players
    default: true

  zCore.announce:
    description: Allows player to announce a message in chat
    default: op

  zCore.rtp:
    description: Allows player to teleport to random location
    default: true

  zCore.enderSee:
    description: Allows player to view another's player ender chest
    default: op

  zCore.invSee:
    description: Allows player to view another's player inventory
    default: op